# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0002_auto_20170201_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='plateno',
            field=models.TextField(null=True),
        ),
    ]
