# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0003_auto_20170201_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='plateno',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='car',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='idno',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='idtype',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='mobile',
        ),
    ]
